### ISSUE TITLE
Custom timeout support

### ISSUE THREAD

**Issue by devlato** [devslash-paul/fetchDSL#20]
Hey – would be great to start supporting customizable timeouts. We noticed lots of _channel closed_ exceptions occurring when we tried to reach [GreatFirewallOfChina](https://en.wikipedia.org/wiki/Great_Firewall)'ed servers. It would be convenient to customize timeouts for such envs, so we could see less annoying exceptions and do less retry attempts.

**Comment by devslash-paul** [comment]
https://github.com/devslash-paul/fetchDSL/pull/21

Will be included in `0.16.0`

**Comment by devslash-paul** [comment]
Merged - 0.16.0 release underway. Configurable via `runHttp({...})` where timeout options are set via a receiver build as fetchDSL itself is. Allows setting of socket timeout, connection timeout, and connection request timeout, as well as following redirects.
