### ISSUE TITLE
Allow `concurrency` to be set on a per call basis

### ISSUE THREAD

**Issue by pault-t-canva** [devslash-paul/fetchDSL#27]
Currently concurrency can only be set on a `runHttp` block. Thus if you want to change concurrency in a subsequent call, you must create a new `runHttp` block and thus lose your session details

**Comment by devslash-paul** [comment]
done in master - will release soon

**Comment by pault-t-canva** [comment]
Whoops, this is a val, make it a var

**Comment by devslash-paul** [comment]
Released in 0.21.0
