### ISSUE TITLE
Add ability to decorate a built request

### ISSUE THREAD

**Issue by pault-t-canva** [devslash-paul/fetchDSL#33]
There are a few examples where it'd be useful to decorate an otherwise built request. At this point, a hook would receive a fully built call. If no change is required, the call can be returned, else the call can be changed and a new call returned. This would make it simple to create rules that require interaction with multiple before/after/urlProvider blocks in ergonomic ways.

Potential syntax

```
runHttp 
  call("...") {
      use(decorator)
   }
}
```

**Comment by pault-t-canva** [comment]
This would also allow the cookie jar before hook to be created via a default hook rather than mutating the call at runtime.

**Comment by devslash-paul** [comment]
This is done via `install`
