### ISSUE TITLE
Add ability to chew up file

### ISSUE THREAD

**Issue by pault-t-canva** [devslash-paul/fetchDSL#7]
It would be useful to have a large file be able to auto-retry from where it failed. This could be done by popping lines off the file in their entirety once they fully succeed the request. 

Then if they don't complete the requests successfully, they're left in the file to re-attempt next time.

**Comment by devslash-paul** [comment]
This is now handled in #17 - i'd prefer we didn't alter the input implicitly and this would only work for a `FileDataSupplier`
